name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: raphael-fretter/actions/.github/workflows/reusable-trivy.yml@main
   with:
      image: 'ghcr.io/raphael-fretter/wordsmith-web:latest'
